### ISSUE TITLE
IndexOutOfBounds Exception when I implement Filterable.

### ISSUE THREAD

**Issue by wanclem** [willblaschko/header-footer-recycler-view#2]
Hello,nice job on HeaderFooterRecyclerView.I am getting an IndexOutOfBoundsException when Implement Filterable on the HeaderFooterAdapter to search mItems..Pls help.Thank you.

**Comment by willblaschko** [comment]
Honestly, I haven't worked with Filterables directly, but my guess would be that you are probably getting back the wrong value for the size of your data, since Filterable would include the headers/footers but then try to access those values (with the header offset) from your list, giving you an OOB exception.

**Comment by wanaclem** [comment]
Oh yea,thanks you are right..The count was the problem.I already figured a way to get around it.Thanks for replying.
